app = 'mkgee-vinyl-notify'
primary_region = 'atl'

[build]

# Remove the http_service section since this is a worker

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Add processes section for background worker
[processes]
  app = "python app.py"

# Prevent auto-stopping
[metrics]
  port = 9091
  path = "/metrics"
